In [2]:
import pandas as pd
import numpy as np

In [5]:
data = pd.read_csv("book.csv", encoding='ISO-8859-1')

In [6]:
df = data.copy()

In [9]:
df.values

array([[1, 276726, 'Classical Mythology', 5],
       [2, 276729, 'Clara Callan', 3],
       [3, 276729, 'Decision in Normandy', 6],
       ...,
       [9998, 162121, 'How to Flirt: A Practical Guide', 7],
       [9999, 162121, 'Twilight', 8],
       [10000, 162129, 'Kids Say the Darndest Things', 6]], dtype=object)

In [11]:
from sklearn.metrics.pairwise import pairwise_distances

# Define two matrices X and Y
X = [[0, 0, 0], [1, 1, 1]]
Y = [[1, 0, 0], [1, 1, 0]]

# Calculate squared Euclidean distances between points in X and Y
distances = pairwise_distances(X, Y, metric='cosine')

print(distances)

[[1.         1.        ]
 [0.42264973 0.18350342]]


In [13]:
len(X)

2

In [15]:
import pandas as pd
from sklearn.metrics.pairwise import pairwise_distances

# Create a DataFrame X
data = [[1, 276726, 3, 5],
        [2, 276729, 2, 3],
        [3, 276729, 6, 6],
        [9998, 162121, 8, 7],
        [9999, 162121, 9, 8],
        [10000, 162129, 11, 6]]

columns = ['Column1', 'Column2', 'Column3', 'Column4']

df = pd.DataFrame(data, columns=columns)

# Single vector Y
# Y = [[1, 1, 1, 0, 0]]

# Calculate cosine similarities
similarities = 1 - pairwise_distances(df.values, metric='cosine')

print(similarities)


[[1.         1.         1.         0.99810403 0.99810366 0.99810346]
 [1.         1.         1.         0.99810426 0.99810388 0.99810369]
 [1.         1.         1.         0.99810448 0.9981041  0.99810391]
 [0.99810403 0.99810426 0.99810448 1.         1.         1.        ]
 [0.99810366 0.99810388 0.9981041  1.         1.         1.        ]
 [0.99810346 0.99810369 0.99810391 1.         1.         1.        ]]


In [16]:
set1 = set(1,2,3,4,5)
set2 = set(6,7,8,9,10)
set1-set2

TypeError: set expected at most 1 argument, got 5